# Generated by Django 2.1.4 on 2019-01-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INN', models.CharField(max_length=12, unique=True)),
                ('abbrev_name', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.CostCenter'),
        ),
    ]
