# Generated by Django 2.1.4 on 2019-01-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20190122_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date',
            new_name='date_planned',
        ),
    ]
