# Generated by Django 2.1.4 on 2019-01-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20190125_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('N', 'Нет'), ('Y', 'Да'), ('P', 'Часть')], default='N', max_length=1),
        ),
    ]
