# Generated by Django 2.1.4 on 2019-01-29 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20190128_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Требуемая сумма'),
        ),
        migrations.AlterField(
            model_name='request',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='request',
            name='costcenter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.CostCenter', verbose_name='ЦФО'),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Customer', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_planned',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Планируемая дата'),
        ),
        migrations.AlterField(
            model_name='request',
            name='purpose',
            field=models.CharField(max_length=100, verbose_name='Назначение платежа'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('N', 'Нет'), ('Y', 'Да'), ('P', 'Часть')], default='N', max_length=1, verbose_name='Оплачено'),
        ),
    ]
