# Generated by Django 2.1.4 on 2019-01-31 07:29

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20190129_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.FileField(upload_to=request.models.user_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='request.Upload', verbose_name='Документы'),
        ),
    ]
