# Generated by Django 2.1.4 on 2019-01-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20190131_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='documents',
            field=models.ManyToManyField(blank=True, to='request.Upload', verbose_name='Вложенные документы'),
        ),
    ]
