# Generated by Django 2.1.4 on 2019-01-31 10:07

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20190131_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_planned',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Планируемая дата'),
        ),
    ]
