# Generated by Django 2.1.4 on 2019-02-02 08:58

from django.db import migrations, models
import django.utils.timezone
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20190131_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='scan',
            field=models.FileField(upload_to=request.models.user_directory_path, verbose_name='Вложенные документы'),
        ),
    ]
