# Generated by Django 2.1.5 on 2019-02-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_auto_20190202_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='scan',
            field=models.FileField(upload_to='scans/', verbose_name='Вложенные документы'),
        ),
    ]
