# Generated by Django 2.1.5 on 2019-02-05 13:30

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_auto_20190205_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='scan',
            field=models.FileField(upload_to=request.models.user_directory_path, verbose_name='Вложенные документы'),
        ),
    ]
