# Generated by Django 2.1.5 on 2019-02-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_upload_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='uploaded_by',
            new_name='user',
        ),
    ]
