# Generated by Django 2.1.5 on 2019-02-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_auto_20190205_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='has_attachments',
            field=models.BooleanField(default=False, verbose_name='Вложения'),
        ),
    ]
